# Generated by Django 5.0.1 on 2024-01-26 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='horario_func',
            field=models.TextField(default=False),
        ),
    ]
